# Generated by Django 6.0.5 on 2026-05-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('profession', models.CharField(max_length=100, verbose_name='Профессия')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('about', models.TextField(verbose_name='О себе')),
            ],
        ),
    ]
