# Generated by Django 6.0.5 on 2026-05-15 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horse_tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Дата тура')),
                ('status', models.CharField(choices=[('pending', 'Ожидание подтверждения'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='horse_tours.tourcompany', verbose_name='Тур-компания')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='horse_tours.person', verbose_name='Клиент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='horse_tours.service', verbose_name='Услуга')),
            ],
        ),
    ]
